// Copyright (c) 2026 Conceal Network, Conceal Devs
// SPDX-License-Identifier: MIT

/**
 * Pre-computed float32 `m8` investment-rate table for termQuarters 1 – 20.
 *
 * Values were generated by running `tools/interest-parity/gen_m8.cpp`
 * (compiled with `g++ -O0 -lm`) which exactly reproduces the daemon's
 * investment interest formula from Currency.cpp:
 *
 *   auto mq = static_cast<float>(1.4473);
 *   float termQuarters = term / 64800;   // integer division then to float
 *   auto m8 = (float)(100.0 * pow(1.0 + (mq / 100.0), termQuarters) - 100.0);
 *
 * Each entry: { quarter, m8, hex }
 *   - quarter  : term / 64800  (1 – 20)
 *   - m8       : the float32 value (stored as JS number, same bit pattern via Math.fround)
 *   - hex      : IEEE-754 float32 bit pattern from C++ memcpy — ground truth
 *
 * DO NOT edit m8 values by hand; re-run the generator and update both the
 * values and hex comments atomically.
 */

export interface InvestmentM8Entry {
  readonly quarter: number;
  readonly m8: number;
  readonly hex: string;
}

export const INVESTMENT_M8: readonly InvestmentM8Entry[] = [
  { quarter: 1, m8: Math.fround(1.447299957), hex: "3FB94120" }, // 0x3FB94120
  { quarter: 2, m8: Math.fround(2.915546656), hex: "403A9851" }, // 0x403A9851
  { quarter: 3, m8: Math.fround(4.405043125), hex: "408CF61D" }, // 0x408CF61D
  { quarter: 4, m8: Math.fround(5.916097641), hex: "40BD50AC" }, // 0x40BD50AC
  { quarter: 5, m8: Math.fround(7.449021339), hex: "40EE5E62" }, // 0x40EE5E62
  { quarter: 6, m8: Math.fround(9.004130363), hex: "411010EB" }, // 0x411010EB
  { quarter: 7, m8: Math.fround(10.58174706), hex: "41294ED6" }, // 0x41294ED6
  { quarter: 8, m8: Math.fround(12.18219662), hex: "4142EA47" }, // 0x4142EA47
  { quarter: 9, m8: Math.fround(13.80580997), hex: "415CE499" }, // 0x415CE499
  { quarter: 10, m8: Math.fround(15.45292187), hex: "41773F2B" }, // 0x41773F2B
  { quarter: 11, m8: Math.fround(17.12387085), hex: "4188FDB0" }, // 0x4188FDB0
  { quarter: 12, m8: Math.fround(18.81900597), hex: "41968D53" }, // 0x41968D53
  { quarter: 13, m8: Math.fround(20.5386734), hex: "41A44F34" }, // 0x41A44F34
  { quarter: 14, m8: Math.fround(22.28322792), hex: "41B2440D" }, // 0x41B2440D
  { quarter: 15, m8: Math.fround(24.05303383), hex: "41C06C9D" }, // 0x41C06C9D
  { quarter: 16, m8: Math.fround(25.84845352), hex: "41CEC9A2" }, // 0x41CEC9A2
  { quarter: 17, m8: Math.fround(27.66985893), hex: "41DD5BDF" }, // 0x41DD5BDF
  { quarter: 18, m8: Math.fround(29.5176239), hex: "41EC2418" }, // 0x41EC2418
  { quarter: 19, m8: Math.fround(31.39213181), hex: "41FB2316" }, // 0x41FB2316
  { quarter: 20, m8: Math.fround(33.29376984), hex: "42052CD2" }, // 0x42052CD2
];
